background_opacity 0.5
background #0f111a
foreground #dcdfe4
foreground #ffffff
#
# background #000000

#
# Font (Terminus TTF)
font_family      Terminus (TTF)
bold_font        auto
italic_font      auto
font_size        8.8

# Layout sạch
disable_ligatures always
# line_height 1.0
# letter_spacing 0

# Fullscreen feel
window_padding_width 0
hide_window_decorations yes
background_opacity 0.9
adjust_column_width 1
