################ PERFORMANCE ################

fps
frametime
frame_timing=0

################ GPU ################

gpu_stats
gpu_list=1
gpu_temp
gpu_core_clock
gpu_power
vram
throttling_status

################ CPU ################

cpu_stats
cpu_mhz
cpu_temp
cpu_power

################ MEMORY ################

ram

################ METRICS ################

fps_metrics=avg,1
fps_text=FPS

################ VISUAL ################

position=middle-left
font_size=25
text_outline
round_corners=6
background_alpha=0.35
# hud_compact

################ LOGGING ################

# log_interval=0
# benchmark_percentiles=97,AVG,1,0.1

toggle_hud=grave
