[Appearance]
color_scheme_path=
custom_palette=false
icon_theme=breeze
style=Fusion

[Fonts]
fixed="monospace,10,-1,5,50,0,0,0,0,0"
general="Noto Sans,10,-1,5,50,0,0,0,0,0"

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x1\xce\0\0\x1\xfa\0\0\0\0\0\0\0\0\0\0\x1\xce\0\0\x1\xfa\0\0\0\0\x2\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\x1\xce\0\0\x1\xfa)
