preload = /home/neon/Pictures/Wallpapers/hyprpaper/1372790.png
preload = /home/neon/Pictures/Wallpapers/hyprpaper/939344.jpg
preload = /home/neon/Pictures/Wallpapers/hyprpaper/full4k.jpg
preload = /home/neon/Pictures/Wallpapers/hyprpaper/illustration-anime-character-rain.jpg

wallpaper = eDP-1, /home/neon/Pictures/Wallpapers/hyprpaper/full4k.jpg
